name: Laravel

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4
    - name: Copy Environment variables
      run: |
            if [ ! -f .env ]; then
              touch .env
              echo "${{ secrets.PROD_ENV_FILE }}" > .env
            fi
    - name: Install Dependencies
      run: composer install
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    # - name: Run migration
    #   run: php artisan migrate
    # - name: Run seed
    #   run: php artisan db:seed
    # - name: Generate passport keys
    #   run: |
    #     if [ ! -f storage/oauth-private.key ] || [ ! -f storage/oauth-public.key ]; then
    #       php artisan passport:install
    #     else
    #       echo "Passport keys already exist"
    #     fi
    - name: Check and create storage link
      run: |
        if [ ! -L public/storage ]; then
          php artisan storage:link
        else
          echo "Storage link already exists"
        fi
